# Generated by Django 4.2.6 on 2023-10-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_payment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='comment',
            new_name='commment',
        ),
    ]
